import pandas as pd
df = pd.read_csv('Carbon Emissions.csv')
print("Data head:")
print(df.head())
print("\nColumns:")
print(df.columns.tolist())
print("\nShape:")
print(df.shape)
print("\nInfo:")
print(df.info())